# -*- coding: utf-8 -*-
"""Project_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zNIkP4nWbruWTGpTnaa6Sa2zL0ABEtxs

##Importing JSON and uploading Record file
"""

import json

fd = open("record.json",'r')
r = fd.read()
fd.close()

record = json.loads(r)

"""##InitialRecord """

record

"""##Sales record with three sample inputs"""

sales_Record={'Sample_data':{'name': '***', 'pr': '***', 'qn': '***','Bg_Amt':'***'},
              'Sample_data1': {'name': '***', 'pr': '***', 'qn': '***','Bg_Amt':'***'},
              'Sample_data2': {'name': '*** ', 'pr': '***', 'qn': '***','Bg_Amt':'***'}}

import json

sales_js = json.dumps(sales_Record)
sales_js

"""##Function To update Record"""

def UpdateRecord(record):
  js = json.dumps(record)
  fd = open("record.json",'w')
  fd.write(js)
  fd.close()

"""##Function to update SalesRecord"""

def Update_SalesRecord(sales_Record):
  sales_js = json.dumps(sales_Record)
  fd = open("sales_Record.json",'w')
  fd.write(sales_js)
  fd.close()

"""##Code"""

Category=input("Are you a Shopkeeper or a Customer? ")

if Category=="Shopkeeper":
  getInfo=input("Are you going to Add/Delete the Products? ")
  if  getInfo!="Add":
    getID=input("Enter the Product ID")
    if getID in record.keys():
      del record[getID]
      print("Deleted Succesfully")
      UpdateRecord(record)
    else:
      print("Not Exist")
  else:
    prod_id = input("Enter product id:")
    if prod_id not in record.keys():
      name = str(input("Enter name:"))
      pr = int(input("Enter price:"))
      qn = int(input("Enter quantity:"))

      record[prod_id] = {'name': name, 'pr': pr, 'qn': qn}
      print("Added Succesfully")
      UpdateRecord(record)
    else:
      print("Already Exist")
elif Category=="Customer":
  ui_prod  = input("Enter the product_Id: ")
  
  if ui_prod in record.keys():
    ui_quant = int(input("Enter the quantity: "))
    if ui_quant!=0 and ui_quant<=record[ui_prod]['qn']:
    
      ne=record[ui_prod]['name']
      p_ce=record[ui_prod]['pr']
      q_ty=record[ui_prod]['qn']
      b_Amt=record[ui_prod]['pr'] * ui_quant
      print("************Invoice****************")
      print("    ***************************")
      print("Product: ",ne)
      print("Price: ", p_ce)
      print("Quantity:", ui_quant )
      print("Billing Amount: ", b_Amt)
      print("    ***************************")
      print("    Thank You for shopping! ")
      print("***********************************")
      sales_Record[ui_prod] = {'Bg_Amt': b_Amt, 'name':ne, 'pr': p_ce, 'qn': ui_quant}
      Update_SalesRecord(sales_Record)

      record[ui_prod]['qn'] = record[ui_prod]['qn'] - ui_quant
      if record[ui_prod]['qn']==0:
        del record[ui_prod]
      UpdateRecord(record)

    elif ui_quant>record[ui_prod]['qn']:
      print(f"In Sufficient Quantity \n Available Quantity {record[ui_prod]['qn']}")
    elif ui_quant<=0:
      print("Invalid Quantity")
    
  else:
       print("Product not Avaliable")

"""##Record after Transaction"""

record

"""### Sales Transactions"""

sales_Record